//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Sep 25 12:07:45 2014 by ROOT version 5.32/00)
//      from the StreamerInfo in file total_nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCElectron_h
#define TCElectron_h
class TCElectron;

#include "TCEGamma.h"
#include "TVector3.h"
#include "Riostream.h"
#include <vector>
#include "TCElectron.h"

class TCElectron : public TCEGamma {

public:
// Nested classes forward declaration.
class HitInfo;

public:
// Nested classes declaration.
class HitInfo {

public:
// Nested classes declaration.

public:
// Data Members.
   int         Layer;       //
   bool        ValidFilter;    //
   bool        PixelFilter;    //
   bool        BarrelPixelFilter;    //
   bool        MuonFilter;           //
   bool        StripFilter;          //
   bool        TrackerFilter;        //

   HitInfo();
   HitInfo(const HitInfo & );
   virtual ~HitInfo();

};

public:
// Data Members.
   TVector3    _pos;        //
   float       _normChi2gsf;    //
   float       _normChi2kf;     //
   float       _ptError;        //
   float       _fBrem;          //
   float       _inverseEnergyMomentumDiff;    //
   float       _EoP;                          //
   float       _EoPout;                       //
   float       _ip3d;                         //
   float       _ip3dSig;                      //
   float       _deltaEtaSeedCluster;          //
   float       _deltaPhiSeedCluster;          //
   bool        _passConvVeto;                 //
   short       _convMissHits;                 //
   int         _trackerLayersWithMeasurement;    //
   int         _numberOfValidHits;               //
   int         _numberOfValidPixelHits;          //
   int         _numberOfValidTrackerHits;        //
   int         _numberOfLostPixelHits;           //
   int         _numberOfLostTrackerHits;         //
   float       _effArea;                         //
   vector<TCElectron::HitInfo> _HitMap;                          //

   TCElectron();
   TCElectron(const TCElectron & );
   virtual ~TCElectron();

   ClassDef(TCElectron,2); // Generated by MakeProject.
};
#endif
