//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Sep 25 12:07:45 2014 by ROOT version 5.32/00)
//      from the StreamerInfo in file total_nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCMuon_h
#define TCMuon_h
class TCMuon;

#include "TCPhysObject.h"

class TCMuon : public TCPhysObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       _ptError;    //
   bool        _isPF;       //
   bool        _isTRK;      //
   bool        _isGLB;      //
   bool        _isSoft;     //
   bool        _isTight;    //
   bool        _isGood;     //
   bool        _isGoodLoose;    //
   float       _caloComp;       //
   float       _segComp;        //
   int         _numberOfMatches;    //
   int         _numberOfMatchedStations;    //
   int         _numberOfValidPixelHits;     //
   int         _numberOfValidTrackerHits;    //
   int         _numberOfLostPixelHits;       //
   int         _numberOfLostTrackerHits;     //
   int         _numberOfValidMuonHits;       //
   int         _trackLayersWithMeasurement;    //
   int         _pixelLayersWithMeasurement;    //
   float       _normalizedChi2;                //
   float       _normalizedChi2_tracker;        //
   float       _pfIsoCharged;                  //
   float       _pfIsoNeutral;                  //
   float       _pfIsoPhoton;                   //

   TCMuon();
   TCMuon(const TCMuon & );
   virtual ~TCMuon();

   ClassDef(TCMuon,2); // Generated by MakeProject.
};
#endif
