//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Sep 25 12:07:45 2014 by ROOT version 5.32/00)
//      from the StreamerInfo in file total_nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCPhoton_h
#define TCPhoton_h
class TCPhoton;

#include "TCEGamma.h"

class TCPhoton : public TCEGamma {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        _trackVeto;    //
   bool        _convVeto;     //
   float       _mipchi2;      //
   float       _miptoten;     //
   float       _mipslope;     //
   float       _mipintercept;    //
   float       _mipnhitcone;     //
   float       _mipishalo;       //
   float       _roundness;       //
   float       _angle;           //
   float       _smin;            //
   float       _smaj;            //

   TCPhoton();
   TCPhoton(const TCPhoton & );
   virtual ~TCPhoton();

   ClassDef(TCPhoton,2); // Generated by MakeProject.
};
#endif
