/********************************************************************
* testProjectDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error testProjectDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabletestProjectDict();
extern void G__cpp_setup_inheritancetestProjectDict();
extern void G__cpp_setup_typetabletestProjectDict();
extern void G__cpp_setup_memvartestProjectDict();
extern void G__cpp_setup_globaltestProjectDict();
extern void G__cpp_setup_memfunctestProjectDict();
extern void G__cpp_setup_functestProjectDict();
extern void G__set_cpp_environmenttestProjectDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "testProjectHeaders.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__testProjectDictLN_TClass;
extern G__linked_taginfo G__testProjectDictLN_TBuffer;
extern G__linked_taginfo G__testProjectDictLN_TMemberInspector;
extern G__linked_taginfo G__testProjectDictLN_TObject;
extern G__linked_taginfo G__testProjectDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__testProjectDictLN_string;
extern G__linked_taginfo G__testProjectDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__testProjectDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testProjectDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__testProjectDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testProjectDictLN_TCMET;
extern G__linked_taginfo G__testProjectDictLN_TVector2;
extern G__linked_taginfo G__testProjectDictLN_TCJet;
extern G__linked_taginfo G__testProjectDictLN_TCPhysObject;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__testProjectDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__testProjectDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__testProjectDictLN_TVector3;
extern G__linked_taginfo G__testProjectDictLN_TLorentzVector;
extern G__linked_taginfo G__testProjectDictLN_pairlEstringcOfloatgR;
extern G__linked_taginfo G__testProjectDictLN_vectorlEpairlEstringcOfloatgRcOallocatorlEpairlEstringcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__testProjectDictLN_reverse_iteratorlEvectorlEpairlEstringcOfloatgRcOallocatorlEpairlEstringcOfloatgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testProjectDictLN_TCElectron;
extern G__linked_taginfo G__testProjectDictLN_TCEGamma;
extern G__linked_taginfo G__testProjectDictLN_TCEGammacLcLCrystalInfo;
extern G__linked_taginfo G__testProjectDictLN_vectorlETCEGammacLcLCrystalInfocOallocatorlETCEGammacLcLCrystalInfogRsPgR;
extern G__linked_taginfo G__testProjectDictLN_reverse_iteratorlEvectorlETCEGammacLcLCrystalInfocOallocatorlETCEGammacLcLCrystalInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testProjectDictLN_TCElectroncLcLHitInfo;
extern G__linked_taginfo G__testProjectDictLN_vectorlETCElectroncLcLHitInfocOallocatorlETCElectroncLcLHitInfogRsPgR;
extern G__linked_taginfo G__testProjectDictLN_reverse_iteratorlEvectorlETCElectroncLcLHitInfocOallocatorlETCElectroncLcLHitInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testProjectDictLN_TCMuon;
extern G__linked_taginfo G__testProjectDictLN_TCPhoton;
extern G__linked_taginfo G__testProjectDictLN_TCGenJet;
extern G__linked_taginfo G__testProjectDictLN_TCGenParticle;
extern G__linked_taginfo G__testProjectDictLN_TCTriggerObject;
extern G__linked_taginfo G__testProjectDictLN_TCPrimaryVtx;

/* STUB derived class for protected member access */
