/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODOUBLESIDEDCB
#define ROODOUBLESIDEDCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooDoubleSidedCB : public RooAbsPdf {
public:
  RooDoubleSidedCB() {} ; 
  RooDoubleSidedCB(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha_L,
	      RooAbsReal& _n_L,
	      RooAbsReal& _alpha_R,
	      RooAbsReal& _n_R);
  RooDoubleSidedCB(const RooDoubleSidedCB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDoubleSidedCB(*this,newname); }
  inline virtual ~RooDoubleSidedCB() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy alpha_L ;
  RooRealProxy n_L ;
  RooRealProxy alpha_R ;
  RooRealProxy n_R ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooDoubleSidedCB,1) // Double Sided CB Function!
};
 
#endif
